CREATE TABLE RES_PRATOS(
PRA_IN_CODIGO INT NOT NULL IDENTITY CONSTRAINT RES_PK_PRATOS PRIMARY KEY,
PRA_ST_NOME VARCHAR(100) NOT NULL,
PRA_ST_DESCRICAO VARCHAR(50) NULL CONSTRAINT RES_DF_PRA_DESCRICAO DEFAULT 'COMIDA BRASILEIRA',
PRA_RE_PRECO NUMERIC(7,2) NOT NULL CONSTRAINT RES_CK_PRA_PRECO CHECK (PRA_RE_PRECO>=0)
)